# Generated by Django 4.0.4 on 2022-05-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
