# Generated by Django 4.0.4 on 2022-05-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0002_clinicianavailability'),
        ('booking', '0002_alter_booking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='clinician_availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician.ClinicianAvailability'),
        ),
    ]
