# Generated by Django 4.0.4 on 2022-05-07 09:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician.clinician')),
            ],
            options={
                'db_table': 'clinician_availability',
            },
        ),
    ]
